{"name": "5. После оформления заказа его номер появляется в разделе В работе", "status": "broken", "statusDetails": {"message": "ValueError: response body:\n{\"message\":\"API rate limit exceeded for 78.107.252.163. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n\nrequest url:\nhttps://api.github.com/repos/mozilla/geckodriver/releases/latest\nresponse headers:\n{'Date': 'Sun, 10 Nov 2024 19:24:05 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1731269001', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '280', 'X-GitHub-Request-Id': 'EDEA:D4745:44563E9:45580DE:67310855'}", "trace": "request = <SubRequest 'driver' for <Function test_order_appears_in_progress_section_after_creation[firefox]>>\n\n    @pytest.fixture(params=[\"chrome\", \"firefox\"], scope=\"function\")\n    def driver(request):\n        browser = request.param\n        with allure.step(f\"Запуск теста в браузере {browser}\"):\n            if browser == \"chrome\":\n                chrome_options = webdriver.ChromeOptions()\n                driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)\n            elif browser == \"firefox\":\n    \n                # Вариант 1: Используем GeckoDriverManager для автоматической загрузки драйвера\n                firefox_options = webdriver.FirefoxOptions()\n>               driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()), options=firefox_options)\n\ntests/conftest.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv/lib/python3.12/site-packages/webdriver_manager/firefox.py:39: in install\n    driver_path = self._get_driver_binary_path(self.driver)\n.venv/lib/python3.12/site-packages/webdriver_manager/core/manager.py:35: in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n.venv/lib/python3.12/site-packages/webdriver_manager/core/driver_cache.py:107: in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n.venv/lib/python3.12/site-packages/webdriver_manager/core/driver_cache.py:154: in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n.venv/lib/python3.12/site-packages/webdriver_manager/core/driver.py:48: in get_driver_version_to_download\n    return self.get_latest_release_version()\n.venv/lib/python3.12/site-packages/webdriver_manager/drivers/firefox.py:29: in get_latest_release_version\n    resp = self._http_client.get(\n.venv/lib/python3.12/site-packages/webdriver_manager/core/http.py:36: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [403]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n            raise ValueError(f\"There is no such driver by url {resp.url}\")\n        elif status_code == 401:\n            raise ValueError(f\"API Rate limit exceeded. You have to add GH_TOKEN!!!\")\n        elif resp.status_code != 200:\n>           raise ValueError(\n                f\"response body:\\n{resp.text}\\n\"\n                f\"request url:\\n{resp.request.url}\\n\"\n                f\"response headers:\\n{dict(resp.headers)}\\n\"\n            )\nE           ValueError: response body:\nE           {\"message\":\"API rate limit exceeded for 78.107.252.163. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\nE           \nE           request url:\nE           https://api.github.com/repos/mozilla/geckodriver/releases/latest\nE           response headers:\nE           {'Date': 'Sun, 10 Nov 2024 19:24:05 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1731269001', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '280', 'X-GitHub-Request-Id': 'EDEA:D4745:44563E9:45580DE:67310855'}\n\n.venv/lib/python3.12/site-packages/webdriver_manager/core/http.py:19: ValueError"}, "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1731266644756, "stop": 1731266644756, "uuid": "ead97181-b57c-44ca-87de-d5e94a35693d", "historyId": "f4137067100363b56ad85babb777a1b3", "testCaseId": "e9068b5ae358a585767524ed1c9459ee", "fullName": "tests.test_04_order_feed.TestOrderFeed#test_order_appears_in_progress_section_after_creation", "labels": [{"name": "story", "value": "4. Раздел «Лента заказов»"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_04_order_feed"}, {"name": "subSuite", "value": "TestOrderFeed"}, {"name": "host", "value": "MBP-Vlad"}, {"name": "thread", "value": "17651-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_04_order_feed"}]}